import os
import json
import smtplib
import sys
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv

# Load Env
load_dotenv()

# Settings
SENDER_EMAIL = "dhuratdipti@gmail.com"
RECEIVER_EMAIL = "diptidhurat12@gmail.com"
EMAIL_APP_PASSWORD = os.getenv("EMAIL_APP_PASSWORD")

# Paths
BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
PULSE_FILE = os.path.join(BASE_DIR, "data", "weekly_pulse.json")

def send_automated_email():
    if not EMAIL_APP_PASSWORD:
        print("❌ Error: EMAIL_APP_PASSWORD not found in environment.")
        sys.exit(1)

    if not os.path.exists(PULSE_FILE):
        print(f"❌ Error: {PULSE_FILE} not found. Run analysis first.")
        sys.exit(1)

    with open(PULSE_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)

    note = data['weekly_note']
    metadata = data.get('metadata', {"generated_at": "N/A"})
    gen_date = metadata.get('generated_at', 'N/A')

    html_content = f"""
    <html>
    <body style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #1e293b; background-color: #f8fafc; padding: 20px;">
        <div style="max-width: 650px; margin: 0 auto; background: white; border: 1px solid #e2e8f0; border-radius: 16px; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);">
            <!-- Header -->
            <div style="background: #00d09c; padding: 30px; text-align: center;">
                <h1 style="color: #0f172a; margin: 0; font-size: 24px; font-weight: 800;">🚀 Weekly Critical Pulse</h1>
                <p style="color: #0f172a; opacity: 0.8; margin: 10px 0 0 0; font-weight: 600;">Groww App Product Health | {gen_date}</p>
            </div>
            
            <div style="padding: 30px;">
                <p style="font-size: 16px;">Hi Team,</p>
                <p>The automated analysis for the week is complete. Here are the top friction points identified from the last 12 weeks of user feedback.</p>

                <!-- Section: Themes -->
                <h3 style="color: #ef4444; border-bottom: 2px solid #fee2e2; padding-bottom: 8px; margin-top: 30px;">🚨 Top 3 Critical Themes</h3>
                <ul style="padding-left: 20px;">
                    {"".join([f"<li style='margin-bottom: 10px;'><b>{t}</b></li>" for t in note['top_3_themes']])}
                </ul>

                <!-- Section: Quotes -->
                <h3 style="color: #3b82f6; border-bottom: 2px solid #dbeafe; padding-bottom: 8px; margin-top: 30px;">💬 User Evidence (Strict Alignment)</h3>
                <div style="background: #f1f5f9; border-left: 4px solid #94a3b8; padding: 15px; font-style: italic; border-radius: 4px;">
                    {"<br><br>".join([f"\"{q}\"" for q in note['user_quotes']])}
                </div>

                <!-- Section: Actions -->
                <h3 style="color: #10b981; border-bottom: 2px solid #d1fae5; padding-bottom: 8px; margin-top: 30px;">🛠️ Recommended Priority Fixes</h3>
                <ul style="list-style: none; padding: 0;">
                    {"".join([f"<li style='background: #ecfdf5; margin-bottom: 10px; padding: 12px; border-radius: 8px; border: 1px solid #d1fae5;'>✅ {i}</li>" for i in note['action_ideas']])}
                </ul>

                <!-- Section: Summary -->
                <div style="margin-top: 40px; padding: 20px; background: #0f172a; color: white; border-radius: 12px;">
                    <b style="color: #00d09c;">Executive Summary:</b><br>
                    <p style="margin: 10px 0 0 0; font-size: 14px; line-height: 1.5; opacity: 0.9;">{note['summary']}</p>
                </div>

                <div style="margin-top: 40px; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 20px;">
                    <a href="https://dipti1201-app-store-review-streamlit-app-i1mru9.streamlit.app/" 
                       style="background: #00d09c; color: #0f172a; padding: 12px 25px; text-decoration: none; border-radius: 8px; font-weight: 700; font-size: 14px;">
                        View Interactive Dashboard
                    </a>
                </div>
            </div>

            <div style="background: #f8fafc; padding: 20px; text-align: center; font-size: 11px; color: #94a3b8; border-top: 1px solid #e2e8f0;">
                This is an automated report generated by the Groww Pulse Engine.<br>
                Analysis Window: Past 12 Weeks | Data Source: Google Play Store
            </div>
        </div>
    </body>
    </html>
    """

    try:
        msg = MIMEMultipart()
        msg['From'] = SENDER_EMAIL
        msg['To'] = RECEIVER_EMAIL
        msg['Subject'] = f"Weekly Critical Pulse - Groww App ({gen_date})"
        msg.attach(MIMEText(html_content, 'html'))

        with smtplib.SMTP("smtp.gmail.com", 587) as server:
            server.starttls()
            server.login(SENDER_EMAIL, EMAIL_APP_PASSWORD)
            server.send_message(msg)
        
        print(f"✅ Automated Weekly Email sent to {RECEIVER_EMAIL}")
    except Exception as e:
        print(f"❌ Failed to send automated email: {e}")
        sys.exit(1)

if __name__ == "__main__":
    send_automated_email()
